[tool.poetry]
name = "ucpr"
version = "0.1.0"
description = ""
authors = ["ucpr <contact@ucpr.dev>"]

[tool.poetry.dependencies]
python = "^3.8"
grip = "^4.5.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
