name: Latest blog post workflow
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Pull in posts
        uses: gautamkrishnar/blog-post-workflow@v1.8.4
        with:
          feed_list: "https://medium.com/feed/@ucpr,https://zenn.dev/ucpr/feed"

